use_frameworks!

platform :ios, '10.0'

target 'VMLocalization_Example' do
  pod 'VMLocalization', :path => '../'

  target 'VMLocalization_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
